name: Deploy Backend on Merge
on:
  push:
    branches:
      - main
    paths:
      - 'Backend/clinic-backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      - name: Change to backend directory and install dependencies
        run: |
          cd Backend/clinic-backend
          npm ci

      - name: Deploy to Google App Engine
        run: |
          cd Backend/clinic-backend
          gcloud app deploy --quiet