name: Deploy Web App on Merge
on:
  push:
    branches:
      - main
    paths:
      - 'WebApp/clinic-web-app/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change to web app directory and install dependencies
        run: |
          cd WebApp/clinic-web-app
          npm ci
      - name: Build the Web App
        run: |
          cd WebApp/clinic-web-app
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLINIC_WEBAPP }}
          channelId: live
          projectId: clinic-webapp
          entryPoint: WebApp/clinic-web-app